### ISSUE TITLE
Dockered sickbeard timing out with /etc/hosts name resolutions

### ISSUE THREAD

**Issue by Alives** [timhaak/docker-sickbeard#7]
Running with this:
```
/usr/bin/docker run -it --link sabnzbdplus:sabnzbdplus --name sickbeard \
  --restart no --rm -h sickbeard -p 127.0.0.1:8081:8081 -v /data:/data \
  -v /etc/localtime:/etc/localtime:ro -v /opt/docker/sickbeard:/config \
  timhaak/sickbeard /bin/bash
```
```
root@sickbeard:/# cat /etc/hosts
172.17.0.20     sickbeard
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.10     sabnzbdplus
```
```
root@sickbeard:/# ping sabnzbdplus
PING sabnzbdplus (172.17.0.10) 56(84) bytes of data.
64 bytes from sabnzbdplus (172.17.0.10): icmp_seq=1 ttl=64 time=0.099 ms
^C
--- sabnzbdplus ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.099/0.099/0.099/0.000 ms
```
```
root@sickbeard:/# (echo 'import urllib'; \
  echo 'if urllib.urlopen("http://sabnzbdplus:8080"):'; \
  echo '  print "Success"') | \
  python
Success
```

But when I put http://sabnzbdplus:8080 in the sickbeard sabnzbdplus host field, it never completes, doesn't log anything, and sits there.  If I use the IP of that container, it's fine.  I suppose that means I either need to statically assign the IP to the container (which seems to be impossible with docker), or I need to get this DNS resolution working somehow.

Any ideas?

**Comment by Alives** [comment]
If I use a shorter name than sabnzbdplus (sab, for example) this works fine.  Interesting.

**Comment by timhaak** [comment]
Interesting which version of docker are you using ?

**Comment by Alives** [comment]
1.5.  I think it's actually an issue with sickbeard as ping, etc all worked with the longer hostname.  Maybe its python/urllib, but when I tried by hand it was fine as you can see above.
